### ISSUE TITLE
Optimisations

### ISSUE THREAD

**Issue by Silence-112** [SilenceIsFatto/modset_generator#1]
### When given every possible modset (modsets key in modsets.json), choice generation can take around 5 seconds on average with 5 choices.

```
{
    "modsets": "random_multiple",
    "desired_climate": ["temperate"],
    "desired_era": "modern",
    "desired_key": "rhs",
    "desired_dlc": ["none"],
    "allow_double_occ": 0,
    "choices": 5,
    "debug_level": 0,
    "force_faction_occ": [],
    "force_faction_inv": [],
    "force_faction_reb": [],
    "force_faction_riv": [],
    "force_faction_civ": []
}
```
* this settings.json will take ~4-6 seconds to return all choices.
* with 10 choices, it takes around ~8-9 seconds.

It may be better to move the "collection", "type" and "era" keys from factions.json to modsets.json. (perhaps adding an optional way to use it in factions.json, if necessary). Since modsets are generally iterated through way less, it'd make more sense to cache the data after grabbing it from there as opposed to grabbing it every time factions are iterated through.

In general, things are checked far too much and more things should be cached if possible.
A lot of the checks seem to be somewhat wasteful - by that I mean, ALL the data is grabbed and THEN discarded, as opposed to NOT grabbing the data at all if it doesn't meet the required validity checks.

Pretty much all of the faction data is stored in an array and then iterated through (this is what SQF does to you), other data structures may be worth using to make data retrieval more efficient.

**Comment by Silence-112** [comment]
Oh yeah, dictionaries exist. Should probably use `json.loads` instead of `json.load`...

**Comment by Silence-112** [comment]
I have rewritten a fair bit of code to utilise dictionaries and to cache the information at initialization as opposed to wasting it every loop.

Will create a PR that links to this issue when I feel it's ready.

### 10 Choices (Before)
* **~8-9 seconds.**

### 10 Choices (After)
* **~1-2 seconds.**

**Comment by SilenceIsFatto** [comment]
Test
